name: PupUp
favicon: null
layout_spectrum: 0.8814
typography_spectrum: 0.39533
title: PupUp Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37786396-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9c797'
    - '#ba8f5d'
    - '#634739'
    - '#1f181b'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
