name: PupUp
favicon: null
layout_spectrum: 0.8814
typography_spectrum: 0.39533
title: PupUp Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37786396-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe100'
    - '#e73834'
    - '#000000'
    - '#fefefe'
    - '#655900'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
