name: PupUp
favicon: null
layout_spectrum: 0.9701775694265962
typography_spectrum: 0.013412189204245806
title: PupUp Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37786396-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9c797'
    - '#ba8f5d'
    - '#634739'
    - '#1f181b'
  brandStrength: 0.5
  lightness: 0.5630380164366215
  saturation: 0.34304342046380043
  rhythmicContrast: 0.39602622552774847
purpose: []
