name: PupUp
favicon: null
layout_spectrum: 0.53581
typography_spectrum: 0.14542
title: PupUp Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37786396-5
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c232d'
    - '#3a5f69'
    - '#303240'
    - '#364855'
    - '#4a3a3c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
